name: Sync dev-current with main

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync-dev-current:
    name: Synchronise dev-current
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync dev-current with main
      run: |
        #!/bin/bash

        # Fetch the latest updates
        echo "INFO: Pulling the latest changes..."
        git pull

        # Ensure we are on the main branch and update it
        echo "INFO: Switching to the main branch..."
        git switch main
        git pull

        # Ensure dev-current branch is up-to-date
        echo "INFO: Switching to the dev-current branch..."
        if git show-ref --verify --quiet refs/heads/dev-current; then
          git switch dev-current
          git pull
        else
          echo "INFO: dev-current branch does not exist."
        fi

        # Check if dev-current is ahead of main
        echo "INFO: Checking if dev-current has unmerged commits..."
        ahead=$(git log main..dev-current --oneline | wc -l || echo 0)

        if [[ $ahead -gt 0 ]]; then
            echo "----------------------------------------------------"
            echo "INFO: dev-current is ahead of main by $ahead commits"
            echo "INFO: No sync will occur."
            echo "Commit list:"
            git log --pretty=format:"  %h %s" main..dev-current
            exit 0
        fi

        # Sync dev-current with main
        echo "INFO: Syncing dev-current with main..."
        git switch main
        if git show-ref --verify --quiet refs/heads/dev-current; then
          git branch -D dev-current
        fi
        git branch dev-current
        git switch dev-current
        git push --force --set-upstream origin dev-current

        echo "INFO: dev-current successfully synced with main."
